"""
IpcsDump Object
"""

import datetime

from ._util import get_header_record
from .exceptions import TsoError
from .util import is_dump


class IpcsDump:
    """
    z/OS dump data set.
    """

    def __init__(self, dsname: str) -> None:
        """
        Constructor for :class:`pyipcs.IpcsDump`.

        Args:
            dsname: Dump data set name.
        """
        if not is_dump(dsname):
            raise TsoError(
                f"Data set {dsname} does not exist or is not a z/OS dump data set."
            )
        self._dsname = dsname
        self._header = self._parse_header_record()

    @property
    def dsname(self) -> str:
        """Dump data set name."""
        return self._dsname

    @property
    def header(self) -> dict | None:
        """Parsed dump header metadata, or ``None`` if the header record was not found."""
        return self._header

    def _parse_header_record(self) -> dict | None:
        """
        Parse the first dump header in the dump data set.

        The metadata is generated by formatting fields from the BLSRPRD Programming interface.

        Returns:
            Metadata containing general information from the first dump header record,
            or ``None`` if the header record could not be found.
        """
        header_record = get_header_record(self)
        if header_record is None:
            return None
        header_metadata = {}

        dump_type_map = {1: "SAD", 2: "SVC", 3: "SYSM", 4: "SLIP"}
        # PRD64DUMPT: Dump type
        header_metadata["dump_type"] = dump_type_map.get(
            int.from_bytes(header_record[36:37], byteorder="big"),
            None,
        )
        # PRDTITLE: Title from dump
        header_metadata["title"] = (
            header_record[88:188].decode("cp037", errors="replace").strip()
        )
        # PRDSNAME: System name
        header_metadata["sysname"] = (
            header_record[204:212].decode("cp037", errors="replace").strip()
        )
        # PRDPRODV: Product version
        header_metadata["version"] = int(header_record[260:262].hex()[3])
        # PRDPRODR: Product release
        header_metadata["release"] = int(header_record[262:264].hex()[3])
        # PRDTODVL: Clock value at time of dump (IBM STCK — microseconds since 1900-01-01)
        stck_value = int.from_bytes(header_record[72:80], byteorder="big") >> 12
        dump_time = datetime.datetime(1900, 1, 1) + datetime.timedelta(
            microseconds=stck_value
        )
        header_metadata["timestamp"] = dump_time.isoformat()

        return header_metadata
